# -*- coding: utf-8 -*-
"""ML_Assign1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GpSP0hu0GPo-dWSlgZ8ODr1xta7X0JiP
"""

#reading the first dataset
import pandas as pd

dataset = pd.read_csv('healthcare_dataset.csv')
dataset.head()

#number of features
len(dataset.columns)

#blood types
dataset['Blood Type'].unique()

#most frequent blood type
dataset['Blood Type'].mode() #or: dataset['Blood Type'].value_counts().idxmax()

#rarest blood type
dataset['Blood Type'].value_counts().idxmin()

#medical conditions
len(dataset['Medical Condition'].unique())

#youngest patient
youngest = dataset[dataset['Age'] == dataset['Age'].min()]
print('The name of the youngest patient is: ', youngest['Name'].iloc[0],
      '\nand his age is ', dataset['Age'].min())

#oldest patient
youngest = dataset[dataset['Age'] == dataset['Age'].max()]
print('The name of the oldest patient is: ', youngest['Name'].iloc[0],
      '\nand his age is ', dataset['Age'].max())

#average billing amount
dataset['Billing Amount'].mean()

#total billing amount across all patients
dataset['Billing Amount'].sum()

#reading the second dataset
import pandas as pd

dataset2 = pd.read_csv('Salaries.csv')
dataset2.head()

#columns between the 2nd and 8th columns, and rows from 1 to 1000
dataset2.iloc[1:1001, 1:9] #note: I included the 2nd and 8th cloumns(from column 2 to 8)

#number of missing values for each feature
dataset2.isnull().sum()

#total count of the missing values in the dataset
dataset2.isnull().sum().sum()

#median value for the "basepay" feature
dataset2['BasePay'].median()